### ISSUE TITLE
not working with new elixir

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [farrrr/laravel-elixir-css-url-adjuster#4]
```
TypeError: Object function (recipe) {
    // We'll start by loading all of the available tasks.
    require('require-dir')('./tasks');


    // The user may then choose which tasks they want.
    recipe(Elixir.mixins);

    // Now that the user has requested their desired tasks
    // from the Gulpfile, we'll initialize everything!
    createGulpTasks.call(Elixir);
} has no method 'queueTask'
    at Function.<anonymous> (/srv/www/displate/node_modules/laravel-elixir-css-url-adjuster/index.js:37:17)
    at Function.<anonymous> (/srv/www/displate/node_modules/laravel-elixir/index.js:44:18)
    at /srv/www/displate/gulpfile.js:28:9
    at Elixir (/srv/www/displate/node_modules/laravel-elixir/index.js:18:5)
    at Object.<anonymous> (/srv/www/displate/gulpfile.js:14:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by farrrr** [comment]
I have already published new version for Elixir 3, just update and enjoy. :)
